spring.application.name=loan-management-system-alpa-2
spring.datasource.url=jdbc:postgresql://localhost:5432/PLMS_Alpha
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8732